import { describe, expect, it } from "vitest";
import { definicaoDoFormulario } from "./catalogo";
import { NOTAS_MEFE } from "./comuns";
import { IDS_FORMULARIO, type IdFormulario } from "./tipos";

/**
 * Fidelidade aos PDFs originais: todo trecho de texto dos três PDFs enviados pelo usuário (extraído com
 * pdftotext, uma linha por trecho, sem unidades soltas, números e rodapés de página) precisa existir na
 * definição digital, com a mesma grafia e acentuação. Se um rótulo mudar sem querer, este teste acusa.
 */
const TEXTOS_DOS_PDFS: Record<IdFormulario, readonly string[]> = {
  mefe: [
    "AVALIAÇÃO MEFE",
    "Adutores – Abertura lateral",
    "Agachamento (Squat)",
    "Altura",
    "Altura alcançada",
    "Altura ÷ tempo de contato",
    "Ambidestro",
    "Amplitude articular ativa e controle do movimento",
    "Aquecimento prévio",
    "Assimetria Hop Test",
    "Assinatura do aluno",
    "Assinatura do(a) avaliador(a) · CREF",
    "Ativa e passiva – goniômetro",
    "Baixa",
    "Banco de Wells – melhor de 3 tentativas",
    "Bastão nas costas – 3 pontos de contato",
    "Boa",
    "Cadência de corrida",
    "Capacidade cardiorrespiratória",
    "Capacidade funcional, padrões de movimento e condicionamento",
    "Classificação",
    "Coluna lombar – Extensão",
    "Coluna lombar – Flexão",
    "Com contramovimento – uso do CAE",
    "Compensação",
    "Compensação lombar e ângulo da coxa",
    "Compensação observada:",
    "Comprimento muscular e amplitude passiva",
    "Conclusão e plano de treinamento",
    "Contato com o solo e passada",
    "Core anti-rotação",
    "Counter Movement Jump (CMJ)",
    "Dados do aluno",
    "Data da avaliação",
    "Data de nascimento",
    "Decúbito dorsal, quadril a 90°",
    "Decúbito ventral – amplitude",
    "Direito",
    "Distância dedos-chão ou Schober",
    "Dobradiça de quadril (Hip Hinge)",
    "Dorsiflexão de tornozelo",
    "Dorsiflexão passiva – joelho estendido",
    "Drop Jump (DJ) – índice RSI",
    "Duração do aquecimento",
    "E",
    "E-mail",
    "EFICIÊNCIA",
    "ELASTICIDADE",
    "Eficiência",
    "Eficiência do movimento",
    "El",
    "Elasticidade",
    "Elasticidade / reatividade",
    "Empurrar (Push)",
    "Equilíbrio das 4 dimensões",
    "Esforço percebido (Borg)",
    "Esquerdo",
    "Exercício: ________________",
    "Extensão passiva da coxa",
    "F",
    "FC ao final do teste",
    "FC de repouso",
    "FC máxima estimada",
    "FLEXIBILIDADE",
    "Family Gym · Avaliação MEFE · Documento de uso interno",
    "Farmer walk – postura e marcha",
    "Feminino",
    "Flexibilidade",
    "Flexibilidade muscular",
    "Flexores de quadril – Teste de Thomas",
    "Flexão de braço máxima",
    "Flexão de braço – controle escapular",
    "Flexão de quadril (SLR)",
    "Flexão, extensão, rotação e inclinação",
    "Força e potência",
    "Força máxima (1RM ou estimado)",
    "Frequência semanal",
    "Gastrocnêmio / sóleo",
    "Glúteo médio / piriforme",
    "Histórico de lesões, cirurgias e contraindicações",
    "Hop Test unilateral",
    "Horário da avaliação",
    "Inline lunge – estabilidade pélvica",
    "Instrumento",
    "Instrutor(a) responsável",
    "Isquiotibiais – Sentar e alcançar",
    "Isquiotibiais – Ângulo poplíteo",
    "Knee-to-wall – distância hálux-parede",
    "Lado dominante",
    "M",
    "MOBILIDADE",
    "Masculino",
    "Mini-hurdles laterais – 5 barreiras",
    "Mobilidade",
    "Mobilidade articular",
    "Mobilidade cervical",
    "Mobilidade torácica (rotação)",
    "Mobilidade · Eficiência · Flexibilidade · Elasticidade",
    "Média",
    "NOTA GERAL MEFE (M + E + F + El) ÷ 4",
    "Nome completo",
    "Nota (1 a 5)",
    "Não",
    "Objetivo principal",
    "Objetivos específicos do plano",
    "Obs. elasticidade",
    "Observações finais do avaliador",
    "Observações – Eficiência",
    "Observações – Flexibilidade",
    "Observações – Mobilidade",
    "Outro",
    "Overhead squat – joelhos e tronco",
    "Padrão e critério",
    "Padrões de movimento funcional",
    "Pallof press – estabilidade do tronco",
    "Passada (Lunge)",
    "Peitoral – Comprimento anterior",
    "Peso",
    "Pontuação geral MEFE",
    "Prancha ventral",
    "Prevenção de lesões",
    "Prioridade de trabalho",
    "Protocolo adotado",
    "Protocolo e condições da avaliação",
    "Psoas / reto femoral – Thomas modif.",
    "Puxar (Pull)",
    "Reatividade no plano frontal",
    "Reavaliação prevista",
    "Remada – retração escapular",
    "Repetições até a falha técnica",
    "Resultado",
    "Retorno elástico, reatividade e stiffness muscular",
    "Rotação de ombro (interna / externa)",
    "Rotação externa passiva do quadril",
    "Rotação interna / externa do quadril",
    "Salto horizontal em 1 perna – assimetria",
    "Salto vertical",
    "Sem pré-estiramento – força concêntrica",
    "Sentado – goniômetro ou fita",
    "Sentado, quadril fixo – estimar graus",
    "Sexo",
    "Sim",
    "Simétrico",
    "Squat Jump (SJ)",
    "Stiffness muscular – palpação",
    "Straight Leg Raise – perna estendida",
    "Supino, braços em abdução",
    "Supino, quadril a 90° – goniômetro",
    "Telefone / WhatsApp",
    "Temperatura ambiente",
    "Tempo / distância",
    "Tempo de sustentação com boa forma",
    "Teste aplicado",
    "Teste e protocolo",
    "Testes específicos por grupo muscular",
    "Transporte de carga (Carry)",
    "Tônus em repouso – avaliação qualitativa",
    "VO2 máx. estimado",
    "Z1 Recuperação",
    "Z2 Aeróbico leve",
    "Z3 Aeróbico moderado",
    "Z4 Limiar",
    "Z5 Máximo",
    "Zona de treinamento predominante",
    "x / sem",
    "°C",
    "Índice elástico (CMJ – SJ) ÷ SJ × 100",
  ],
  nutricional: [
    "% do VET",
    "1. Você provoca vômito porque se sente desconfortavelmente cheio(a)?",
    "1ª medida",
    "1–2x por",
    "1–3x por mês",
    "2. Você se preocupa por ter perdido o controle sobre o quanto come?",
    "2ª medida",
    "3. Você perdeu mais de 6 kg em um período de 3 meses recentemente?",
    "3ª medida",
    "3–6x por",
    "4. Você se acha gordo(a) quando outras pessoas dizem que você está",
    "5. Você diria que a comida domina a sua vida?",
    "ANTROPOMETRIA E COMPOSIÇÃO CORPORAL",
    "ATIVIDADE FÍSICA E PLANO NUTRICIONAL",
    "AVALIAÇÃO NUTRICIONAL",
    "Abdominal",
    "Abdômen",
    "Alergias e intolerâncias alimentares",
    "Alimentos, preparações e quantidades",
    "Almoço",
    "Altura",
    "Altura da cicatriz umbilical",
    "Amarela",
    "Amendoim / oleaginosas",
    "Anamnese · Composição corporal · Consumo alimentar · Plano",
    "Anemia",
    "Antebraço",
    "Anticoncepcional",
    "Apenas a Psicologia",
    "Apenas o(a) instrutor(a)",
    "As informações deste documento são dados pessoais sensíveis de saúde (LGPD) e serão usadas apenas para",
    "Assinatura do(a) cliente",
    "Atividade física",
    "Aumentado",
    "Autorizo compartilhar informações pertinentes com",
    "Aversões alimentares",
    "Axilar média",
    "Azia / queimação",
    "Baixo",
    "Bebida alcoólica",
    "Bebidas alcoólicas",
    "Belisca entre as refeições",
    "Bicipital",
    "Bioimpedância (se disponível)",
    "Boa",
    "Braço contraído – direito",
    "Braço contraído – esquerdo",
    "Braço relaxado – direito",
    "Braço relaxado – esquerdo",
    "CRN",
    "Café da manhã",
    "Cansaço excessivo",
    "Carboidratos",
    "Cardápio fixo",
    "Carnes, ovos e peixes",
    "Ceia",
    "Cereais integrais",
    "Ciclo menstrual",
    "Cintura",
    "Circunferências",
    "Cirurgias prévias (incluindo bariátrica)",
    "Clara",
    "Classificação do IMC",
    "Clínico geral",
    "Colesterol / triglicerídeos altos",
    "Colesterol total",
    "Com frequência",
    "Come por ansiedade ou emoção",
    "Come usando telas (TV, celular)",
    "Comportamento alimentar",
    "Compulsão por doces",
    "Consentimento",
    "Consistência das fezes (Escala de Bristol)",
    "Constipação",
    "Controle de doença / saúde",
    "Cor da urina",
    "Coxa",
    "Coxa proximal – direita",
    "Coxa proximal – esquerda",
    "Creatinina",
    "Cunningham",
    "Cálculo energético",
    "Câimbras",
    "Dados do cliente",
    "Data da avaliação",
    "Data de nascimento",
    "Data do exame",
    "Densidade corporal",
    "Devagar",
    "Diabetes / pré-diabetes",
    "Diarreia",
    "Distribuição de macronutrientes",
    "Diário",
    "Dobra",
    "Dobras cutâneas",
    "Doces e sobremesas",
    "Doença cardiovascular",
    "Doença renal",
    "Doenças e condições diagnosticadas",
    "Dose",
    'Duas ou mais respostas "Sim" sugerem investigação mais detalhada e encaminhamento à Psicologia.',
    "Duração",
    "Durnin & Womersley",
    "Déficit calórico",
    "E-mail",
    "Educação física (ajuste do treino)",
    "Em quanto tempo",
    "Emagrecimento",
    "Embutidos (presunto, salsicha, salame)",
    "Encaminhamentos",
    "Endocrinologia",
    "Equipamento utilizado",
    "Escura",
    "Esteatose hepática",
    "Estilo de vida",
    "Estratégia",
    "Estufamento / gases",
    "Evacuações",
    "Ex-fumante",
    "Exame",
    "Exames bioquímicos",
    "FAO / OMS",
    "Family Gym · Avaliação Nutricional · Documento confidencial",
    "Fast food / delivery",
    "Fator atividade",
    "Faulkner",
    "Feijão e outras leguminosas",
    "Feminino",
    "Ferritina",
    "Fibras",
    "Fome noturna",
    "Frequência",
    "Frequência de consumo",
    "Frituras",
    "Frutas",
    "Frutos do mar",
    "Fórmula utilizada",
    "Ganho de massa muscular",
    "Gasto energético total",
    "Gasto energético, metas, macronutrientes e conduta",
    "Gastrite / refluxo",
    "Gastroenterologia",
    "Gestante / lactante",
    "Gestação / lactação",
    "Glicemia de jejum",
    "Glúten / doença celíaca",
    "Gordura corporal",
    "Gordura visceral",
    "Gorduras",
    "Grupo de alimentos",
    "HDL",
    "HISTÓRICO CLÍNICO",
    "Harris-Benedict",
    "Hemoglobina",
    "Hemoglobina glicada (HbA1c)",
    "Hipertensão",
    "Hipo ou hipertireoidismo",
    "Histórico familiar (diabetes, cardiopatia, obesidade, câncer)",
    "Horas de sono",
    "Horário",
    "Horário de trabalho / estudo",
    "Horário do treino",
    "HÁBITOS E CONSUMO ALIMENTAR",
    "IMC",
    "Idade",
    "Ingestão de água",
    "Insulina de jejum",
    "Intensa",
    "Intensidade",
    "Irregular",
    "Jackson & Pollock – 3 dobras",
    "Jackson & Pollock – 7 dobras",
    "Jantar",
    "Jejum intermitente",
    "Katch-McArdle",
    "L / dia",
    "LDL",
    "Lactose",
    "Lanche da manhã",
    "Lanche da tarde",
    "Leite e derivados",
    "Leve",
    "Levemente ativo",
    "Lista de substituições",
    "Local",
    "Low carb",
    "Maior perímetro glúteo",
    "Manutenção",
    "Masculino",
    "Massa gorda",
    "Massa magra",
    "Massa muscular esquelética",
    "Medicamentos e suplementos em uso",
    "Medidas gerais",
    "Medidas, dobras cutâneas, bioimpedância e exames",
    "Menopausa",
    "Menor perímetro do tronco",
    "Meta calórica",
    "Metas de curto prazo (próximas 4 semanas)",
    "Mifflin-St Jeor",
    "Modalidade(s)",
    "Modelo de plano",
    "Moderada",
    "Moderadamente ativo",
    "Motivo / prescritor",
    "Muito ativo",
    "Muito aumentado",
    "Média",
    "Nenhum",
    "Nenhuma conhecida",
    "Nome",
    "Nome completo",
    "Normal",
    "Nunca",
    "Nunca / raro",
    "Nutricionista responsável",
    "Nutricionista responsável · CRN",
    "Nutriente",
    "Náusea",
    "Não",
    "Não autorizo",
    "Não se aplica",
    "Nível de atividade no dia a dia",
    "Nível de estresse",
    "Objetivo nas palavras do cliente e prazo esperado",
    "Objetivo principal",
    "Observação",
    "Oleaginosas e sementes",
    "Onívoro",
    "Orientações e conduta",
    "Osteoporose / osteopenia",
    "Outra",
    "Outra (descrever abaixo)",
    "Outras condições de saúde",
    "Outro",
    "Ovo",
    "Padrão alimentar",
    "Panturrilha medial",
    "Panturrilha – direita",
    "Panturrilha – esquerda",
    "Peitoral",
    "Performance esportiva",
    "Pergunta",
    "Pescoço",
    "Peso atual",
    "Peso desejado",
    "Peso usual",
    "Petroski",
    "Plano flexível",
    "Preferências alimentares",
    "Profissão / ocupação",
    "Proteína do leite",
    "Proteínas",
    "Protocolo",
    "Pré-treino",
    "Psicologia",
    "Pós-treino",
    "Quadril",
    "Qualidade do sono",
    "Queda de cabelo",
    "Quem prepara as refeições",
    "Recordatório alimentar de 24 horas",
    "Recordatório de 24 horas, frequência alimentar e comportamento",
    "Reeducação alimentar",
    "Refeição",
    "Refeições fora de casa",
    "Refrigerantes e sucos industrializados",
    "Registre tudo o que foi consumido no dia anterior, com preparações, marcas e quantidades (medidas caseiras",
    "Regular",
    "Relação cintura / estatura",
    "Relação cintura / quadril",
    "Resultado",
    "Retenção de líquidos",
    "Retorno previsto",
    "Risco pela cintura",
    "Ruim",
    "Rápido",
    "SCOFF · Rastreio de transtornos alimentares",
    "Salgadinhos e ultraprocessados",
    "Saúde, medicamentos, sintomas e estilo de vida",
    "Sedentário",
    "Semanal",
    "Sempre",
    "Sexo",
    "Sim",
    "Sinais, sintomas e funcionamento intestinal",
    "Sintomas frequentes",
    "Social",
    "Soja",
    "Subescapular",
    "Superávit calórico",
    "Suplementação prescrita",
    "Suplemento",
    "Suprailíaca",
    "Síndrome do intestino irritável",
    "Síndrome dos ovários policísticos",
    "TGO / TGP",
    "TSH",
    "Tabagismo",
    "Taxa metabólica basal",
    "Telefone / WhatsApp",
    "Tentativas anteriores de dieta (o que funcionou e o que não funcionou)",
    "Tipo 1",
    "Tipo 2",
    "Tipo 3",
    "Tipo 4",
    "Tipo 5",
    "Tipo 6",
    "Tipo 7",
    "Toda a equipe Family Gym",
    "Todo dia",
    "Tricipital",
    "Triglicerídeos",
    "Tórax",
    "Unhas fracas",
    "Valor de referência",
    "Variação recente",
    "Vegano",
    "Vegetariano",
    "Velocidade ao comer",
    "Verduras e legumes",
    "Vitamina B12",
    "Vitamina D (25-OH)",
    "cliente.",
    "g / dia",
    "g / kg",
    "magro(a)?",
    "o acompanhamento nutricional. O compartilhamento com a equipe Family Gym depende da autorização do",
    "ou gramas).",
    "x / semana",
    "Às vezes",
    "Ácido úrico",
    "Água",
    "Água corporal total",
    "Ângulo de fase",
  ],
  psicologica: [
    '"Avaliação de risco").',
    "1 = discordo totalmente · 2 = discordo · 3 = neutro · 4 = concordo · 5 = concordo totalmente",
    "1. Pouco interesse ou pouco prazer em fazer as",
    "1. Sentir-se nervoso(a), ansioso(a) ou muito",
    "2. Não ser capaz de impedir ou de controlar as",
    "2. Sentir-se para baixo, deprimido(a) ou sem",
    "3. Dificuldade para pegar no sono ou permanecer",
    "3. Preocupar-se muito com diversas coisas",
    "4. Dificuldade para relaxar",
    "4. Sentir-se cansado(a) ou com pouca energia",
    "5. Falta de apetite ou comer demais",
    "5. Ficar tão agitado(a) que se torna difícil",
    "6. Ficar facilmente aborrecido(a) ou irritado(a)",
    "6. Sentir-se mal consigo mesmo(a), ou achar que é",
    "7. Dificuldade para se concentrar nas coisas, como",
    "7. Sentir medo como se algo horrível fosse",
    "8. Lentidão para se movimentar ou falar, a ponto de",
    "9. Pensar em se ferir de alguma maneira ou que",
    "ANAMNESE E CONTEXTO DE VIDA",
    "AVALIAÇÃO PSICOLÓGICA",
    "Acesso a meios (medicamentos, armas, outros)",
    "Acompanhamento psicológico anterior",
    "Acompanhamento psiquiátrico anterior ou atual",
    "Acorda cedo demais",
    "Acorda várias vezes",
    "Alguma dificuldade",
    "Alivia o estresse e me faz sentir bem",
    "Alto",
    "Amigos",
    "Anabolizantes / hormônios sem prescrição",
    "Ansiedade ou preocupação",
    "Apenas a Nutrição",
    "Apenas o(a) instrutor(a)",
    "As informações deste documento são sigilosas, conforme o Código de Ética Profissional do Psicólogo, e são",
    "Assinatura do(a) cliente",
    'Atenção ao item 9: qualquer resposta diferente de "Nenhuma vez" exige avaliação de risco imediata (quadro',
    "Ausente",
    "Autoavaliação nas últimas 2 semanas",
    "Autoeficácia",
    "Autolesão sem intenção suicida",
    "Autopercepção, qualidade do sono e estratégias de enfrentamento",
    "Autorizo compartilhar informações pertinentes com",
    "Avaliação de risco",
    "Ação",
    "Baixo",
    "Barreiras percebidas",
    "Beber álcool",
    "Bebidas alcoólicas",
    "Boa",
    "CRP",
    "Cafeína após as 16h",
    "Cannabis",
    "Cansaço",
    "Classificação",
    "Clínico geral / endocrinologia",
    "Cochilos de dia",
    "Colegas de trabalho",
    "Com que frequência você…",
    "Com quem mora",
    "Come grandes quantidades com sensação de",
    "Comer em excesso",
    "Como você avalia…",
    "Compara o seu corpo com o de outras pessoas",
    "Comunidade / religião",
    "Conduta adotada",
    "Conflitos familiares",
    "Contato com rede de apoio",
    "Contato de emergência (nome, vínculo e telefone)",
    "Contemplação",
    "Contexto de vida e rotina",
    "Conversar com alguém",
    "Cuidado com filhos / família",
    "Custo",
    "Dados do cliente",
    "Data da avaliação",
    "Data de nascimento",
    "Desemprego / dificuldade financeira",
    "Despertares por noite",
    "Detalhes sobre eventos relevantes",
    "Diagnósticos prévios informados",
    "Dificuldade para iniciar o sono",
    "Diário",
    "Doença própria ou de familiar",
    "Dor ou lesão",
    "Dormir mais",
    "Dose",
    "E-mail",
    "ESTRESSE, SONO E BEM-ESTAR",
    "Educação física (ajuste do treino)",
    "Emergência (SAMU 192 / UPA)",
    "Encaminhado por",
    "Encaminhamento psiquiátrico",
    "Encaminhamentos",
    "Energia e disposição",
    "Energéticos e estimulantes",
    "Escolaridade",
    "Escore total GAD-7",
    "Escore total PHQ-9",
    "Estado civil",
    "Estou cansado(a)",
    "Estou desanimado(a) ou triste",
    "Estou viajando ou fora da rotina",
    "Estratégias de enfrentamento",
    "Estágio de prontidão para mudança",
    "Eu treino porque…",
    "Eventos estressantes nos últimos 12 meses",
    "Evita espelhos, fotos ou roupas justas",
    "Expectativas em relação ao acompanhamento",
    "Extrema dificuldade",
    "Falta de motivação",
    "Falta de tempo",
    "Family Gym · Avaliação Psicológica · Documento sigiloso",
    "Família",
    "Fatores de proteção presentes (vínculos, projetos, religiosidade)",
    "Faz dietas muito restritivas ou pula refeições para",
    "Feminino",
    "Fica insatisfeito(a) com o seu corpo",
    "Fisioterapia",
    "Frequente",
    "Frequência das sessões",
    "GAD-7 · Sintomas de ansiedade",
    "Gosto do convívio com outras pessoas",
    "Gosto e me divirto treinando",
    "Grave 15–21",
    "Grave 20–27",
    "Grupo de apoio",
    "HUMOR E ANSIEDADE",
    "Histórico de saúde mental",
    "Histórico de saúde mental, substâncias, rotina e rede de apoio",
    "Horas de trabalho / estudo",
    "Horas dormidas por noite",
    "Horário",
    "Horário em que acorda",
    "Horário em que deita",
    "Idade",
    "Ideação suicida atual",
    "Imagem corporal e comportamento alimentar",
    "Impressões clínicas, objetivos, encaminhamentos e consentimento",
    "Informado o CVV – 188",
    "Iniciativa própria",
    'Instrumentos de rastreio, não de diagnóstico. Pergunta-base: "Nas últimas 2 semanas, com que frequência',
    "Instrutor(a)",
    "Internação psiquiátrica",
    "Investigar",
    "Irritabilidade",
    "Isolar-se",
    "Lazer, hobbies e interesses",
    "Leve 5–9",
    "Luto / perda importante",
    "Mais da",
    "Manutenção",
    "Marque de 0 a 10, em que 0 = nada / muito ruim e 10 = extremamente / excelente.",
    "Masculino",
    "Me sinto culpado(a) quando não treino",
    "Medicamento",
    "Medicamentos em uso",
    "Meditar / respirar",
    "Mensal",
    "Mod. grave 15–19",
    "Modalidade",
    "Moderada 10–14",
    "Moderado",
    "Motivação em geral",
    "Motivação para treinar",
    "Motivação, autoeficácia, barreiras e imagem corporal",
    "Motivo da procura / queixa principal (nas palavras do cliente)",
    "Mudança de casa ou cidade",
    "Muita dificuldade",
    "Muito boa",
    "Médico(a)",
    "Mínima 0–4",
    "Nas últimas 2 semanas…",
    "Nascimento de filho(a)",
    "Nenhuma dificuldade",
    "Nenhuma vez",
    "Nome completo",
    "Nunca",
    "Nutricionista",
    "Nutrição",
    "Nº de filhos",
    "Nº de sessões previstas",
    "Não",
    "Não autorizo",
    "Não sabe",
    "Não tenho companhia",
    "Não vejo muito sentido, mas acabo vindo",
    "Não ver resultados",
    "Nível de estresse no dia a dia",
    "Nível de risco estimado",
    "Objetivos do acompanhamento",
    "Observações comportamentais (aparência, discurso, afeto, atenção, contato)",
    "Observações sobre estresse e sono",
    "Observações sobre o plano",
    "Online",
    "Os resultados demoram a aparecer",
    "Outras pessoas me cobram ou pressionam",
    "Outras substâncias",
    "Outro",
    "Outro profissional",
    "PHQ-9 · Sintomas depressivos",
    "Parceiro(a)",
    "Pensamentos de morte ou de que seria melhor estar morto(a)",
    "Pesadelos frequentes",
    "Plano de segurança elaborado",
    "Plano ou método definido",
    "Pouca ou nenhuma",
    "Praticar exercício",
    "Preparação",
    "Prescrito por / desde quando",
    "Presencial",
    "Profissão / ocupação",
    "Pré-contemplação",
    "Pré-treinos, termogênicos, cafeína em excesso",
    "Psicoeducação e orientação",
    "Psicólogo(a) responsável",
    "Psicólogo(a) responsável · CRP",
    "Psiquiatria",
    "Qualidade do sono",
    "Qualidade dos relacionamentos",
    "Quando está estressado(a), costuma…",
    "Quase todos",
    "Queixas de sono",
    "Quero mudar minha aparência",
    "Quinzenal",
    "Quão difícil os sintomas tornaram o trabalho, a casa ou os relacionamentos?",
    "RELAÇÃO COM O EXERCÍCIO E O CORPO",
    "Raramente",
    "Rastreio com PHQ-9 e GAD-7 (instrumentos de domínio público)",
    "Reavaliação prevista",
    "Rede de apoio",
    "Registro da avaliação de risco",
    "Regular",
    'Respostas "Frequente" ou "Sempre" nos quatro últimos itens indicam investigação de transtorno alimentar e',
    "Ronco / pausas na respiração",
    "Ruim",
    "Satisfação com a vida",
    "Satisfação com trabalho / estudos",
    "Saúde mental · Bem-estar · Relação com o exercício",
    "Semanal",
    "Sempre",
    "Sente culpa depois de comer",
    "Separação ou divórcio",
    "Sexo",
    "Sigilo e consentimento",
    "Sim",
    "Sobrecarga no trabalho",
    "Sono",
    "Sonolência diurna excessiva",
    "Substância",
    "SÍNTESE E PLANO",
    "Síntese e hipóteses clínicas",
    "Tabaco / cigarro eletrônico",
    "Telas antes de dormir",
    "Telefone / WhatsApp",
    "Tempo para adormecer",
    "Tenho confiança de que consigo treinar mesmo quando…",
    "Tenho pouco tempo",
    "Tentativa(s) de suicídio anterior(es)",
    "Toda a equipe Family Gym",
    "Trabalhar mais",
    "Transporte / distância",
    "Transtornos mentais na família",
    "Treina em excesso para compensar o que comeu",
    "Turno de trabalho",
    "Usa laxantes, diuréticos ou vômito para controlar o",
    "Usar telas / redes sociais",
    "Uso de substâncias",
    "Valorizo os benefícios para a minha saúde",
    "Vergonha / desconforto no ambiente",
    "Verifica o corpo repetidamente (espelho, medidas,",
    "Violência ou trauma",
    "Vários dias (1)",
    "acontecer",
    "agitado(a) que fica andando de um lado para o",
    "alinhamento com a Nutrição.",
    "autorização do cliente e se limita ao necessário para o cuidado.",
    "balança)",
    "coisas",
    "compensar",
    "dados pessoais sensíveis de saúde (LGPD). O compartilhamento com a equipe Family Gym só ocorre com",
    "dias (2)",
    "dormindo, ou dormir mais do que de costume",
    "ler ou ver televisão",
    "mesmo(a)",
    "metade dos",
    "os dias (3)",
    "outras pessoas perceberem; ou o oposto, estar tão",
    "outro mais do que de costume",
    "perda de controle",
    "permanecer sentado(a)",
    "perspectiva",
    "peso",
    "preocupações",
    "seria melhor estar morto(a)",
    "tenso(a)",
    "um fracasso ou que decepcionou sua família ou a si",
    'você foi incomodado(a) por algum dos problemas abaixo?"',
    "Às vezes",
  ],
};

/** Rótulos que a tela tem e o PDF não: acrescentados de propósito, e só estes. */
const ACRESCENTADOS: Record<IdFormulario, readonly string[]> = {
  mefe: [],
  nutricional: ["Outra alergia ou intolerância (descrever)"],
  psicologica: [],
};

function rotulosDaGrade(id: IdFormulario): string[] {
  return definicaoDoFormulario(id).paginas.flatMap((p) =>
    p.blocos.flatMap((b) => (b.tipo === "grade" ? b.itens.map((i) => i.rotulo) : [])),
  );
}

function texto(id: IdFormulario): string {
  const d = definicaoDoFormulario(id);
  const t: string[] = [d.tituloFaixa, d.subtituloFaixa, d.rodape];
  for (const p of d.paginas) {
    for (const b of p.blocos) {
      switch (b.tipo) {
        case "secao":
          t.push(b.selo, b.titulo, b.subtitulo);
          break;
        case "subtitulo":
        case "nota":
          t.push("texto" in b ? b.texto : "");
          break;
        case "grade":
          for (const i of b.itens) {
            t.push(i.rotulo);
            if (i.tipo === "campo" && i.unidade) t.push(i.unidade);
            if (i.tipo === "escolha") t.push(...i.opcoes.map((o) => o.rotulo));
          }
          break;
        case "testes":
          t.push("Teste e protocolo", "Direito", "Esquerdo", "Resultado", "Classificação");
          t.push("Baixa", "Média", "Boa");
          for (const l of b.linhas) t.push(l.nome, l.detalhe ?? "", l.campoExtra ?? "", l.unidade);
          break;
        case "padroes":
          t.push("Padrão e critério", "Compensação", "Simétrico", "Nota (1 a 5)", "Sim", "Não");
          t.push("Compensação observada:");
          for (const l of b.linhas) t.push(l.nome, l.detalhe);
          break;
        case "tabela":
          t.push(...b.colunas.map((c) => c.titulo), b.colunaRotulo?.titulo ?? "");
          for (const l of b.linhas) {
            t.push(l.titulo ?? "", l.detalhe ?? "");
            for (const c of Object.values(l.celulas)) if (c.unidade) t.push(c.unidade);
          }
          break;
        case "matriz":
          t.push(b.cabecalho, ...b.opcoes.map((o) => o.rotulo));
          for (const l of b.linhas) t.push(l.texto, l.detalhe ?? "");
          break;
        case "pontuacao-mefe":
          t.push("Pontuação geral MEFE", "NOTA GERAL MEFE", "(M + E + F + El) ÷ 4");
          for (const n of NOTAS_MEFE) t.push(n.letra, n.nome);
          break;
        case "assinaturas":
          t.push(b.esquerda, b.direita);
          break;
        default:
          break;
      }
    }
  }
  return t.join("\n").replace(/\s+/g, " ");
}

describe.each(IDS_FORMULARIO)("fidelidade ao PDF: %s", (id) => {
  const presente = texto(id);

  it("todos os textos do PDF estão na definição digital", () => {
    // No PDF, "Exercício: ________" é um rótulo seguido de uma linha para escrever (aqui, um campo).
    const limpo = (t: string) => t.replace(/_+/g, "").replace(/\s+/g, " ").trim();
    const ausentes = TEXTOS_DOS_PDFS[id].filter((t) => !presente.includes(limpo(t)));
    expect(ausentes).toEqual([]);
  });

  it("não há campo na tela que o PDF não tenha, fora os acrescentados de propósito", () => {
    const pdf = TEXTOS_DOS_PDFS[id].join("\n");
    const inventados = rotulosDaGrade(id).filter(
      (r) => !pdf.includes(r) && !ACRESCENTADOS[id].includes(r),
    );
    expect(inventados).toEqual([]);
  });
});
