/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ModalidadesRouteImport } from './routes/modalidades'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ValoresRouteImport } from './routes/valores'
import { Route as AuthenticatedAulasRouteImport } from './routes/_authenticated/aulas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPrescricaoTreinosRouteImport } from './routes/_authenticated/prescricao-treinos'
import { Route as AuthenticatedRegistrarAvaliacaoRouteImport } from './routes/_authenticated/registrar-avaliacao'
import { Route as AuthenticatedTermosRouteImport } from './routes/_authenticated/termos'
import { Route as AuthenticatedVinculosRouteImport } from './routes/_authenticated/vinculos'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAulasRouteImport } from './routes/app/aulas'
import { Route as AppAvaliacoesRouteImport } from './routes/app/avaliacoes'
import { Route as AppPerfilRouteImport } from './routes/app/perfil'
import { Route as AppPlanoRouteImport } from './routes/app/plano'
import { Route as AppResultadosRouteImport } from './routes/app/resultados'
import { Route as AppSegurancaRouteImport } from './routes/app/seguranca'
import { Route as AppTreinosIndexRouteImport } from './routes/app/treinos/index'
import { Route as AppTreinosTreinoIdRouteImport } from './routes/app/treinos/$treinoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalidadesRoute = ModalidadesRouteImport.update({
  id: '/modalidades',
  path: '/modalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ValoresRoute = ValoresRouteImport.update({
  id: '/valores',
  path: '/valores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAulasRoute = AuthenticatedAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrescricaoTreinosRoute =
  AuthenticatedPrescricaoTreinosRouteImport.update({
    id: '/prescricao-treinos',
    path: '/prescricao-treinos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegistrarAvaliacaoRoute =
  AuthenticatedRegistrarAvaliacaoRouteImport.update({
    id: '/registrar-avaliacao',
    path: '/registrar-avaliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTermosRoute = AuthenticatedTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVinculosRoute = AuthenticatedVinculosRouteImport.update({
  id: '/vinculos',
  path: '/vinculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAulasRoute = AppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacoesRoute = AppAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanoRoute = AppPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AppRoute,
} as any)
const AppResultadosRoute = AppResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AppRoute,
} as any)
const AppSegurancaRoute = AppSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinosIndexRoute = AppTreinosIndexRouteImport.update({
  id: '/treinos/',
  path: '/treinos/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinosTreinoIdRoute = AppTreinosTreinoIdRouteImport.update({
  id: '/treinos/$treinoId',
  path: '/treinos/$treinoId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/modalidades': typeof ModalidadesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/valores': typeof ValoresRoute
  '/aulas': typeof AuthenticatedAulasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/prescricao-treinos': typeof AuthenticatedPrescricaoTreinosRoute
  '/registrar-avaliacao': typeof AuthenticatedRegistrarAvaliacaoRoute
  '/termos': typeof AuthenticatedTermosRoute
  '/vinculos': typeof AuthenticatedVinculosRoute
  '/app/aulas': typeof AppAulasRoute
  '/app/avaliacoes': typeof AppAvaliacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/resultados': typeof AppResultadosRoute
  '/app/seguranca': typeof AppSegurancaRoute
  '/app/': typeof AppIndexRoute
  '/app/treinos/$treinoId': typeof AppTreinosTreinoIdRoute
  '/app/treinos/': typeof AppTreinosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/modalidades': typeof ModalidadesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/valores': typeof ValoresRoute
  '/aulas': typeof AuthenticatedAulasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/prescricao-treinos': typeof AuthenticatedPrescricaoTreinosRoute
  '/registrar-avaliacao': typeof AuthenticatedRegistrarAvaliacaoRoute
  '/termos': typeof AuthenticatedTermosRoute
  '/vinculos': typeof AuthenticatedVinculosRoute
  '/app/aulas': typeof AppAulasRoute
  '/app/avaliacoes': typeof AppAvaliacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/resultados': typeof AppResultadosRoute
  '/app/seguranca': typeof AppSegurancaRoute
  '/app': typeof AppIndexRoute
  '/app/treinos/$treinoId': typeof AppTreinosTreinoIdRoute
  '/app/treinos': typeof AppTreinosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/modalidades': typeof ModalidadesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/valores': typeof ValoresRoute
  '/_authenticated/aulas': typeof AuthenticatedAulasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/prescricao-treinos': typeof AuthenticatedPrescricaoTreinosRoute
  '/_authenticated/registrar-avaliacao': typeof AuthenticatedRegistrarAvaliacaoRoute
  '/_authenticated/termos': typeof AuthenticatedTermosRoute
  '/_authenticated/vinculos': typeof AuthenticatedVinculosRoute
  '/app/aulas': typeof AppAulasRoute
  '/app/avaliacoes': typeof AppAvaliacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/resultados': typeof AppResultadosRoute
  '/app/seguranca': typeof AppSegurancaRoute
  '/app/': typeof AppIndexRoute
  '/app/treinos/$treinoId': typeof AppTreinosTreinoIdRoute
  '/app/treinos/': typeof AppTreinosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/modalidades'
    | '/reset-password'
    | '/valores'
    | '/aulas'
    | '/dashboard'
    | '/financeiro'
    | '/planos'
    | '/prescricao-treinos'
    | '/registrar-avaliacao'
    | '/termos'
    | '/vinculos'
    | '/app/aulas'
    | '/app/avaliacoes'
    | '/app/perfil'
    | '/app/plano'
    | '/app/resultados'
    | '/app/seguranca'
    | '/app/'
    | '/app/treinos/$treinoId'
    | '/app/treinos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/modalidades'
    | '/reset-password'
    | '/valores'
    | '/aulas'
    | '/dashboard'
    | '/financeiro'
    | '/planos'
    | '/prescricao-treinos'
    | '/registrar-avaliacao'
    | '/termos'
    | '/vinculos'
    | '/app/aulas'
    | '/app/avaliacoes'
    | '/app/perfil'
    | '/app/plano'
    | '/app/resultados'
    | '/app/seguranca'
    | '/app'
    | '/app/treinos/$treinoId'
    | '/app/treinos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/modalidades'
    | '/reset-password'
    | '/valores'
    | '/_authenticated/aulas'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/planos'
    | '/_authenticated/prescricao-treinos'
    | '/_authenticated/registrar-avaliacao'
    | '/_authenticated/termos'
    | '/_authenticated/vinculos'
    | '/app/aulas'
    | '/app/avaliacoes'
    | '/app/perfil'
    | '/app/plano'
    | '/app/resultados'
    | '/app/seguranca'
    | '/app/'
    | '/app/treinos/$treinoId'
    | '/app/treinos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ModalidadesRoute: typeof ModalidadesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ValoresRoute: typeof ValoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modalidades': {
      id: '/modalidades'
      path: '/modalidades'
      fullPath: '/modalidades'
      preLoaderRoute: typeof ModalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valores': {
      id: '/valores'
      path: '/valores'
      fullPath: '/valores'
      preLoaderRoute: typeof ValoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aulas': {
      id: '/_authenticated/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AuthenticatedAulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescricao-treinos': {
      id: '/_authenticated/prescricao-treinos'
      path: '/prescricao-treinos'
      fullPath: '/prescricao-treinos'
      preLoaderRoute: typeof AuthenticatedPrescricaoTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registrar-avaliacao': {
      id: '/_authenticated/registrar-avaliacao'
      path: '/registrar-avaliacao'
      fullPath: '/registrar-avaliacao'
      preLoaderRoute: typeof AuthenticatedRegistrarAvaliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/termos': {
      id: '/_authenticated/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof AuthenticatedTermosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vinculos': {
      id: '/_authenticated/vinculos'
      path: '/vinculos'
      fullPath: '/vinculos'
      preLoaderRoute: typeof AuthenticatedVinculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aulas': {
      id: '/app/aulas'
      path: '/aulas'
      fullPath: '/app/aulas'
      preLoaderRoute: typeof AppAulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avaliacoes': {
      id: '/app/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/app/avaliacoes'
      preLoaderRoute: typeof AppAvaliacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plano': {
      id: '/app/plano'
      path: '/plano'
      fullPath: '/app/plano'
      preLoaderRoute: typeof AppPlanoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resultados': {
      id: '/app/resultados'
      path: '/resultados'
      fullPath: '/app/resultados'
      preLoaderRoute: typeof AppResultadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seguranca': {
      id: '/app/seguranca'
      path: '/seguranca'
      fullPath: '/app/seguranca'
      preLoaderRoute: typeof AppSegurancaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinos/': {
      id: '/app/treinos/'
      path: '/treinos'
      fullPath: '/app/treinos/'
      preLoaderRoute: typeof AppTreinosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinos/$treinoId': {
      id: '/app/treinos/$treinoId'
      path: '/treinos/$treinoId'
      fullPath: '/app/treinos/$treinoId'
      preLoaderRoute: typeof AppTreinosTreinoIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAulasRoute: typeof AuthenticatedAulasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPrescricaoTreinosRoute: typeof AuthenticatedPrescricaoTreinosRoute
  AuthenticatedRegistrarAvaliacaoRoute: typeof AuthenticatedRegistrarAvaliacaoRoute
  AuthenticatedTermosRoute: typeof AuthenticatedTermosRoute
  AuthenticatedVinculosRoute: typeof AuthenticatedVinculosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAulasRoute: AuthenticatedAulasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPrescricaoTreinosRoute: AuthenticatedPrescricaoTreinosRoute,
  AuthenticatedRegistrarAvaliacaoRoute: AuthenticatedRegistrarAvaliacaoRoute,
  AuthenticatedTermosRoute: AuthenticatedTermosRoute,
  AuthenticatedVinculosRoute: AuthenticatedVinculosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AppRouteChildren {
  AppAulasRoute: typeof AppAulasRoute
  AppAvaliacoesRoute: typeof AppAvaliacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanoRoute: typeof AppPlanoRoute
  AppResultadosRoute: typeof AppResultadosRoute
  AppSegurancaRoute: typeof AppSegurancaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTreinosTreinoIdRoute: typeof AppTreinosTreinoIdRoute
  AppTreinosIndexRoute: typeof AppTreinosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAulasRoute: AppAulasRoute,
  AppAvaliacoesRoute: AppAvaliacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanoRoute: AppPlanoRoute,
  AppResultadosRoute: AppResultadosRoute,
  AppSegurancaRoute: AppSegurancaRoute,
  AppIndexRoute: AppIndexRoute,
  AppTreinosTreinoIdRoute: AppTreinosTreinoIdRoute,
  AppTreinosIndexRoute: AppTreinosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ModalidadesRoute: ModalidadesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ValoresRoute: ValoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
